default: &default
  adapter: postgresql
  username: ryanvalle
  password:
  host: localhost

development:
  <<: *default
  database: tallii_dev_db

test:
  <<: *default
  database: tallii_test_db
  
production:
  <<: *default
  database: tallii_db
